# Camera rotation calculator

Calculate the rotation needed for the cameras to focus on a same point

The depth layer choice of the cameras needs to be a staggered matrix (see the other notebook)

Peduncle extender original pad dimension: 25, -10. Original Z placement: -3.

In [1]:
import numpy as np

In [2]:
# all distance in millimeters
d = 1070
gap = 33
d_gap = 12 # 10 should be sufficient, but layer 0 lense tip may touch layer 3 PCB
layer_map = np.array([
    [0, 1, 0, 1],
    [3, 2, 3, 2],
    [0, 1, 0, 1],
    [3, 2, 3, 2]
]) # choose this, for its 1) row-wise repeat 2) reasonable corner cases
m,n = layer_map.shape
letter_label = ['A', 'B', 'C', 'D']
number_label = np.arange(4,0,-1)
ori_pad2 = -10
ori_zoff = -3

tilt_flower = True
extend_peduncle = False

In [3]:
if tilt_flower:
    print("========== Tilting flower, entending peduncle ==========")
else:
    print("========== Tilting connector ==========")
for b in range(n):
    for a in range(m):
        d_off = layer_map[a,b]*d_gap
        act_d = d-d_off
        gapX = (a-m/2+1/2)*gap
        gapY = (b-n/2+1/2)*gap
        angleX = np.arctan(gapX/act_d)
        angleY = np.arctan(gapY/act_d*np.cos(angleX))
        
        out_line = "Connector {}{}:\t".format(letter_label[b],number_label[a])
        if extend_peduncle:
            out_line = out_line + \
            "peduncle has padding {: >3}, z offset {: >3}. ".format("{:d}".format(ori_pad2+d_off), 
                                                                          "{:d}".format(ori_zoff+d_off))
        if tilt_flower:
            out_line = out_line + \
                  "flower euler angle X={: >6}, Y={: >6}.".format("{:.3f}".format(angleX/np.pi*180), 
                                                                  "{:.3f}".format(angleY/np.pi*180))
        else:
            out_line = out_line + \
                  "connector euler angle X={: >6}, Y={: >6}.".format("{:.3f}".format(-angleX/np.pi*180), 
                                                                     "{:.3f}".format(-angleY/np.pi*180))
        print(out_line)

========== Tilting flower, entending peduncle ==========
Connector A4:	flower euler angle X=-2.649, Y=-2.646.
Connector A3:	flower euler angle X=-0.914, Y=-2.740.
Connector A2:	flower euler angle X= 0.883, Y=-2.648.
Connector A1:	flower euler angle X= 2.741, Y=-2.738.
Connector B4:	flower euler angle X=-2.679, Y=-0.893.
Connector B3:	flower euler angle X=-0.904, Y=-0.904.
Connector B2:	flower euler angle X= 0.893, Y=-0.893.
Connector B1:	flower euler angle X= 2.709, Y=-0.903.
Connector C4:	flower euler angle X=-2.649, Y= 0.883.
Connector C3:	flower euler angle X=-0.914, Y= 0.914.
Connector C2:	flower euler angle X= 0.883, Y= 0.883.
Connector C1:	flower euler angle X= 2.741, Y= 0.913.
Connector D4:	flower euler angle X=-2.679, Y= 2.676.
Connector D3:	flower euler angle X=-0.904, Y= 2.709.
Connector D2:	flower euler angle X= 0.893, Y= 2.678.
Connector D1:	flower euler angle X= 2.709, Y= 2.706.


In [4]:
# test margin, test corner cases
thickness = 7.6
width = 40
down = width/2*(np.sin(4.283/180*np.pi)+np.sin(4.271/180*np.pi))
up = width/2*(np.sin(-4.200/180*np.pi)+np.sin(1.399/180*np.pi))
print("Margin is {:.3f}".format(d_gap-thickness-down-up))

Margin is 2.393


In [5]:
print(layer_map)

[[0 1 0 1]
 [3 2 3 2]
 [0 1 0 1]
 [3 2 3 2]]
