# Camera rotation calculator

Calculate the rotation needed for the cameras to focus on a same point

Peduncle extender original pad dimension: 25, -10. Original Z placement: -3.

## How to find a proper depth array

Define a matrix *non-overlapping* if it contains only 1,2,3,4, and there's no equal adjacent (including diagonal) elements in it. 

Starts from the top-left corner   
[[1, 2],   
 [3, 4]]
 
Then make a function `top_pad`, expand any NxN matrix to (N+1)xN. The extra top row only needs to consider the original top row. 

First, fill all "determined" elements, where the three elements under it contain 3 different values.

Then, starts from the left, determine all undefined numbers.

By transposing and top_pad again the transpose bace, we make it 3x3.

In [1]:
import numpy as np

In [ ]:
def top_pad(mat):
    """
    mat should be a mxn matrix, containing only 0,1,2,3, non-overlapping
    """
    # pick out original top row, build extra row
    top_vec = mat[0]
    N = len(top_vec)
    assert N>=2
    pad_vec = np.full_like(top_vec, -1)
    
    # fill all "determined" elements in extra row
    for a in range(N-2):
        ref = np.unique(top_vec[a:a+3])
        if len(ref)==3:
            pad_vec[a+1] = 10-np.sum(ref)
    
    # fill all left-outs, where tree-like structure introduced
    for a in range(N):
        if pad_vec

In [ ]:
stop

In [15]:
# all distance in millimeters
d = 700
gap = 33
d_gap = 13
layer_map = np.array([
    [0, 1, 0, 1],
    [2, 3, 2, 3],
    [0, 1, 0, 1],
    [2, 3, 2, 3]
])
m,n = layer_map.shape
letter_label = ['A', 'B', 'C', 'D']
number_label = np.arange(4,0,-1)
ori_pad2 = -10
ori_zoff = -3

In [16]:
for b in range(n):
    for a in range(m):
        d_off = layer_map[a,b]*d_gap
        act_d = d-d_off
        gapX = (a-m/2+1/2)*gap
        gapY = (b-n/2+1/2)*gap
        angleX = np.arctan(gapX/act_d)
        angleY = np.arctan(gapY/act_d*np.cos(angleX))
        
        print("Connector {}{}:\t".format(letter_label[b],number_label[a]) + \
              "peduncle has padding {: >3}, z offset {: >3}. ".format("{:d}".format(ori_pad2+d_off), 
                                                                      "{:d}".format(ori_zoff+d_off)) + \
              "flower euler angle X={: >6}, Y={: >6}.".format("{:.3f}".format(angleX/np.pi*180), 
                                                              "{:.3f}".format(angleY/np.pi*180)))

Connector A4:	peduncle has padding -10, z offset  -3. flower euler angle X=-4.045, Y=-4.035.
Connector A3:	peduncle has padding  16, z offset  23. flower euler angle X=-1.402, Y=-4.199.
Connector A2:	peduncle has padding -10, z offset  -3. flower euler angle X= 1.350, Y=-4.044.
Connector A1:	peduncle has padding  16, z offset  23. flower euler angle X= 4.200, Y=-4.189.
Connector B4:	peduncle has padding   3, z offset  10. flower euler angle X=-4.121, Y=-1.372.
Connector B3:	peduncle has padding  29, z offset  36. flower euler angle X=-1.430, Y=-1.429.
Connector B2:	peduncle has padding   3, z offset  10. flower euler angle X= 1.376, Y=-1.375.
Connector B1:	peduncle has padding  29, z offset  36. flower euler angle X= 4.283, Y=-1.426.
Connector C4:	peduncle has padding -10, z offset  -3. flower euler angle X=-4.045, Y= 1.347.
Connector C3:	peduncle has padding  16, z offset  23. flower euler angle X=-1.402, Y= 1.402.
Connector C2:	peduncle has padding -10, z offset  -3. flower euler ang

In [18]:
# test margin, test D1 and C1
thickness = 7.6
width = 40
down = width/2*(np.sin(4.170/180*np.pi)+np.sin(4.159/180*np.pi))
up = width/2*(np.sin(4.127/180*np.pi)+np.sin(1.374/180*np.pi))
print("Margin is {:.3f}".format(d_gap-thickness-down-up))

Margin is 0.035


In [19]:
print(layer_map)

[[0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]]
