# Camera rotation calculator

Calculate the rotation needed for the cameras to focus on a same point

The depth layer choice of the cameras needs to be a staggered matrix (see the other notebook)

Peduncle extender original pad dimension: 25, -10. Original Z placement: -3.

In [1]:
import numpy as np

In [2]:
# all distance in millimeters
d = 700
gap = 33
d_gap = 12
layer_map = np.array([
    [0, 1, 0, 1],
    [3, 2, 3, 2],
    [0, 1, 0, 1],
    [3, 2, 3, 2]
]) # choose this, for its 1) row-wise repeat 2) reasonable corner cases
m,n = layer_map.shape
letter_label = ['A', 'B', 'C', 'D']
number_label = np.arange(4,0,-1)
ori_pad2 = -10
ori_zoff = -3

In [3]:
for b in range(n):
    for a in range(m):
        d_off = layer_map[a,b]*d_gap
        act_d = d-d_off
        gapX = (a-m/2+1/2)*gap
        gapY = (b-n/2+1/2)*gap
        angleX = np.arctan(gapX/act_d)
        angleY = np.arctan(gapY/act_d*np.cos(angleX))
        
        print("Connector {}{}:\t".format(letter_label[b],number_label[a]) + \
              "peduncle has padding {: >3}, z offset {: >3}. ".format("{:d}".format(ori_pad2+d_off), 
                                                                      "{:d}".format(ori_zoff+d_off)) + \
              "flower euler angle X={: >6}, Y={: >6}.".format("{:.3f}".format(angleX/np.pi*180), 
                                                              "{:.3f}".format(angleY/np.pi*180)))

Connector A4:	peduncle has padding -10, z offset  -3. flower euler angle X=-4.045, Y=-4.035.
Connector A3:	peduncle has padding  26, z offset  33. flower euler angle X=-1.423, Y=-4.262.
Connector A2:	peduncle has padding -10, z offset  -3. flower euler angle X= 1.350, Y=-4.044.
Connector A1:	peduncle has padding  26, z offset  33. flower euler angle X= 4.263, Y=-4.252.
Connector B4:	peduncle has padding   2, z offset   9. flower euler angle X=-4.115, Y=-1.370.
Connector B3:	peduncle has padding  14, z offset  21. flower euler angle X=-1.398, Y=-1.398.
Connector B2:	peduncle has padding   2, z offset   9. flower euler angle X= 1.374, Y=-1.373.
Connector B1:	peduncle has padding  14, z offset  21. flower euler angle X= 4.188, Y=-1.394.
Connector C4:	peduncle has padding -10, z offset  -3. flower euler angle X=-4.045, Y= 1.347.
Connector C3:	peduncle has padding  26, z offset  33. flower euler angle X=-1.423, Y= 1.423.
Connector C2:	peduncle has padding -10, z offset  -3. flower euler ang

In [4]:
# test margin, test corner cases
thickness = 7.6
width = 40
down = width/2*(np.sin(4.283/180*np.pi)+np.sin(4.271/180*np.pi))
up = width/2*(np.sin(4.200/180*np.pi)+np.sin(-1.399/180*np.pi))
print("Margin is {:.3f}".format(d_gap-thickness-down-up))

Margin is 0.440


In [5]:
print(layer_map)

[[0 1 0 1]
 [3 2 3 2]
 [0 1 0 1]
 [3 2 3 2]]
